CREATE SCHEMA BIND_VARIABLES_EXAMPLE_SCHEMA;

SET search_path TO BIND_VARIABLES_EXAMPLE_SCHEMA;

-- Table to help demonstrate SQL injection.
CREATE TABLE ACCOUNTS (
    ACCOUNT_ID INTEGER NOT NULL PRIMARY KEY,
    ACCOUNT_NAME VARCHAR(50) NOT NULL,
    ACCOUNT_BALANCE MONEY NOT NULL
);

